[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://digitalportfolio-yqde.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# This redirect ensures that all routes are handled by the SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
